--
-- PostgreSQL database dump
--

-- Dumped from database version 14.2 (Debian 14.2-1.pgdg110+1)
-- Dumped by pg_dump version 14.2 (Debian 14.2-1.pgdg110+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ambassador_details; Type: TABLE; Schema: public; Owner: AmbassadorProgram
--

CREATE TABLE public.ambassador_details (
    id bigint NOT NULL,
    first_name character varying(100) NOT NULL,
    referral_code character varying(15) NOT NULL,
    member_id bigint
);


ALTER TABLE public.ambassador_details OWNER TO "AmbassadorProgram";

--
-- Name: ambassador_details_id_seq; Type: SEQUENCE; Schema: public; Owner: AmbassadorProgram
--

ALTER TABLE public.ambassador_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ambassador_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: databasechangelog; Type: TABLE; Schema: public; Owner: AmbassadorProgram
--

CREATE TABLE public.databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


ALTER TABLE public.databasechangelog OWNER TO "AmbassadorProgram";

--
-- Name: databasechangeloglock; Type: TABLE; Schema: public; Owner: AmbassadorProgram
--

CREATE TABLE public.databasechangeloglock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);


ALTER TABLE public.databasechangeloglock OWNER TO "AmbassadorProgram";

--
-- Name: member; Type: TABLE; Schema: public; Owner: AmbassadorProgram
--

CREATE TABLE public.member (
    id bigint NOT NULL,
    parent_member_id integer DEFAULT 0 NOT NULL,
    smpl_chain_wallet_address character varying(200) NOT NULL,
    date_created timestamp without time zone DEFAULT now() NOT NULL,
    program_id bigint
);


ALTER TABLE public.member OWNER TO "AmbassadorProgram";

--
-- Name: member_id_seq; Type: SEQUENCE; Schema: public; Owner: AmbassadorProgram
--

ALTER TABLE public.member ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: program; Type: TABLE; Schema: public; Owner: AmbassadorProgram
--

CREATE TABLE public.program (
    id bigint NOT NULL,
    name character varying(250) NOT NULL,
    vendor_id bigint
);


ALTER TABLE public.program OWNER TO "AmbassadorProgram";

--
-- Name: program_id_seq; Type: SEQUENCE; Schema: public; Owner: AmbassadorProgram
--

ALTER TABLE public.program ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.program_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: program_wallet; Type: TABLE; Schema: public; Owner: AmbassadorProgram
--

CREATE TABLE public.program_wallet (
    id bigint NOT NULL,
    distribution_address character varying(50) NOT NULL,
    smpl_chain_wallet_address character varying(50) NOT NULL,
    program_id bigint
);


ALTER TABLE public.program_wallet OWNER TO "AmbassadorProgram";

--
-- Name: program_wallet_id_seq; Type: SEQUENCE; Schema: public; Owner: AmbassadorProgram
--

ALTER TABLE public.program_wallet ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.program_wallet_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transaction; Type: TABLE; Schema: public; Owner: AmbassadorProgram
--

CREATE TABLE public.transaction (
    id bigint NOT NULL,
    smpl_transaction_id character varying(66) NOT NULL,
    transaction_amount numeric(25,10),
    transaction_date timestamp without time zone DEFAULT now() NOT NULL,
    member_id bigint,
    purchasing_member_id bigint NOT NULL,
    transaction_type_id integer
);


ALTER TABLE public.transaction OWNER TO "AmbassadorProgram";

--
-- Name: transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: AmbassadorProgram
--

ALTER TABLE public.transaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transaction_type; Type: TABLE; Schema: public; Owner: AmbassadorProgram
--

CREATE TABLE public.transaction_type (
    id integer NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.transaction_type OWNER TO "AmbassadorProgram";

--
-- Name: transaction_type_id_seq; Type: SEQUENCE; Schema: public; Owner: AmbassadorProgram
--

ALTER TABLE public.transaction_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vendor; Type: TABLE; Schema: public; Owner: AmbassadorProgram
--

CREATE TABLE public.vendor (
    id bigint NOT NULL,
    name character varying(250) NOT NULL
);


ALTER TABLE public.vendor OWNER TO "AmbassadorProgram";

--
-- Name: vendor_id_seq; Type: SEQUENCE; Schema: public; Owner: AmbassadorProgram
--

ALTER TABLE public.vendor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vendor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: ambassador_details; Type: TABLE DATA; Schema: public; Owner: AmbassadorProgram
--

COPY public.ambassador_details (id, first_name, referral_code, member_id) FROM stdin;
1	Bob	123456	1
\.


--
-- Data for Name: databasechangelog; Type: TABLE DATA; Schema: public; Owner: AmbassadorProgram
--

COPY public.databasechangelog (id, author, filename, dateexecuted, orderexecuted, exectype, md5sum, description, comments, tag, liquibase, contexts, labels, deployment_id) FROM stdin;
1647443443836-1	Jacob	db/changelogs/20220316-01-changelog.xml	2022-08-01 22:13:31.752061	1	EXECUTED	8:ad94302d6f40d5e86f2856d11c4b6336	createTable tableName=ambassador_details		\N	4.9.1	\N	\N	9392011581
1647443443836-2	Jacob	db/changelogs/20220316-01-changelog.xml	2022-08-01 22:13:31.76799	2	EXECUTED	8:69251359c016f1c26fe73845883845da	createTable tableName=member		\N	4.9.1	\N	\N	9392011581
1647443443836-3	Jacob	db/changelogs/20220316-01-changelog.xml	2022-08-01 22:13:31.780142	3	EXECUTED	8:343746f8998a97a1b20c1d9636da2153	createTable tableName=program		\N	4.9.1	\N	\N	9392011581
1647443443836-4	Jacob	db/changelogs/20220316-01-changelog.xml	2022-08-01 22:13:31.790207	4	EXECUTED	8:be466e1f11e070b825e0cbb8f5a7ad26	createTable tableName=program_wallet		\N	4.9.1	\N	\N	9392011581
1647443443836-5	Jacob	db/changelogs/20220316-01-changelog.xml	2022-08-01 22:13:31.799935	5	EXECUTED	8:30ac6197db9cb968c6b73b05161d9417	createTable tableName=transaction		\N	4.9.1	\N	\N	9392011581
1647443443836-6	Jacob	db/changelogs/20220316-01-changelog.xml	2022-08-01 22:13:31.810137	6	EXECUTED	8:702fc0b5ef097da7a88122a00437ce44	createTable tableName=transaction_type		\N	4.9.1	\N	\N	9392011581
1647443443836-7	Jacob	db/changelogs/20220316-01-changelog.xml	2022-08-01 22:13:31.818557	7	EXECUTED	8:9f89bb5dd56c7c6feed26b4090713684	createTable tableName=vendor		\N	4.9.1	\N	\N	9392011581
1647443443836-8	Jacob	db/changelogs/20220316-01-changelog.xml	2022-08-01 22:13:31.823718	8	EXECUTED	8:557f9dff2b6f68f4e19b66198dfcd3a4	addUniqueConstraint constraintName=uc_776f680af5de038e995b11711, tableName=transaction_type		\N	4.9.1	\N	\N	9392011581
1647443443836-9	Jacob	db/changelogs/20220316-01-changelog.xml	2022-08-01 22:13:31.831918	9	EXECUTED	8:ab771a3d321518f5cc81d4b2b961a7ce	addUniqueConstraint constraintName=uc_77f53c26c241950bb29b13015, tableName=program_wallet		\N	4.9.1	\N	\N	9392011581
1647443443836-10	Jacob	db/changelogs/20220316-01-changelog.xml	2022-08-01 22:13:31.839743	10	EXECUTED	8:5f2142d41315e7004e7a16d67214073d	addUniqueConstraint constraintName=uc_8b620b42a99ff4cda0a6b8cc0, tableName=vendor		\N	4.9.1	\N	\N	9392011581
1647443443836-11	Jacob	db/changelogs/20220316-01-changelog.xml	2022-08-01 22:13:31.847452	11	EXECUTED	8:e81c5fd648240f3dc963625cd5fd554c	addUniqueConstraint constraintName=uc_9a45533329d6651ba500ac344, tableName=program		\N	4.9.1	\N	\N	9392011581
1647443443836-12	Jacob	db/changelogs/20220316-01-changelog.xml	2022-08-01 22:13:31.854548	12	EXECUTED	8:f52d39ef9d745cfd5d7afb61901d8a62	addUniqueConstraint constraintName=uc_ambassador_details_referral_code, tableName=ambassador_details		\N	4.9.1	\N	\N	9392011581
1647443443836-13	Jacob	db/changelogs/20220316-01-changelog.xml	2022-08-01 22:13:31.871944	13	EXECUTED	8:6cb0bc0a63cbbdadf3f3be8427c31927	addUniqueConstraint constraintName=uc_fa4cd0b19f045539972f86cd9, tableName=member		\N	4.9.1	\N	\N	9392011581
1647443443836-14	Jacob	db/changelogs/20220316-01-changelog.xml	2022-08-01 22:13:31.879917	14	EXECUTED	8:63603a63d9495fd429a930b82dcafcf4	createIndex indexName=idx_0743ddfef21ec86529da92baa, tableName=ambassador_details		\N	4.9.1	\N	\N	9392011581
1647443443836-15	Jacob	db/changelogs/20220316-01-changelog.xml	2022-08-01 22:13:31.886664	15	EXECUTED	8:d7d11cbd63b4be3366530f37c3dc2118	createIndex indexName=idx_94cc9117908d8719763c23bff, tableName=transaction		\N	4.9.1	\N	\N	9392011581
1647443443836-16	Jacob	db/changelogs/20220316-01-changelog.xml	2022-08-01 22:13:31.895538	16	EXECUTED	8:1bc9c3d86889f4a5890fddfd0dbff4f2	createIndex indexName=idx_f578c838501976455ff38cabb, tableName=member		\N	4.9.1	\N	\N	9392011581
1647443443836-17	Jacob	db/changelogs/20220316-01-changelog.xml	2022-08-01 22:13:31.901419	17	EXECUTED	8:269f54b0c7f0ec492721bd42e23ab8ba	addForeignKeyConstraint baseTableName=ambassador_details, constraintName=FK_AMBASSADOR_DETAILS_ON_MEMBER, referencedTableName=member		\N	4.9.1	\N	\N	9392011581
1647443443836-18	Jacob	db/changelogs/20220316-01-changelog.xml	2022-08-01 22:13:31.908032	18	EXECUTED	8:1b6484cf9e7bc3a9c5f3ca97aa470201	addForeignKeyConstraint baseTableName=member, constraintName=FK_MEMBER_ON_PROGRAM, referencedTableName=program		\N	4.9.1	\N	\N	9392011581
1647443443836-19	Jacob	db/changelogs/20220316-01-changelog.xml	2022-08-01 22:13:31.912327	19	EXECUTED	8:e65c607c4b2df8d63c36abc221325253	addForeignKeyConstraint baseTableName=program, constraintName=FK_PROGRAM_ON_VENDOR, referencedTableName=vendor		\N	4.9.1	\N	\N	9392011581
1647443443836-20	Jacob	db/changelogs/20220316-01-changelog.xml	2022-08-01 22:13:31.918665	20	EXECUTED	8:d350599544b967ddda27a2e78169bf46	addForeignKeyConstraint baseTableName=program_wallet, constraintName=FK_PROGRAM_WALLET_ON_PROGRAM, referencedTableName=program		\N	4.9.1	\N	\N	9392011581
1647443443836-21	Jacob	db/changelogs/20220316-01-changelog.xml	2022-08-01 22:13:31.922557	21	EXECUTED	8:3a4974bf57b4f0de709045a1a46fb4ef	addForeignKeyConstraint baseTableName=transaction, constraintName=FK_TRANSACTION_ON_MEMBER, referencedTableName=member		\N	4.9.1	\N	\N	9392011581
1647443443836-22	Jacob	db/changelogs/20220316-01-changelog.xml	2022-08-01 22:13:31.93084	22	EXECUTED	8:c88f8cdff5025d464f5131e6bcbf7be8	addForeignKeyConstraint baseTableName=transaction, constraintName=FK_TRANSACTION_ON_TRANSACTION_TYPE, referencedTableName=transaction_type		\N	4.9.1	\N	\N	9392011581
1647443443836-23	Jacob	db/changelogs/20220316-01-changelog.xml	2022-08-01 22:13:31.936002	23	EXECUTED	8:58d8858b0b417d59874a643107880663	insert tableName=vendor; insert tableName=program; insert tableName=transaction_type; insert tableName=transaction_type		\N	4.9.1	\N	\N	9392011581
1	Jacob	db/changelogs/20220414-01-changelog.xml	2022-08-01 22:13:31.94583	24	EXECUTED	8:7dcf480401300e7d4a77a15009f7d8dd	insert tableName=vendor; insert tableName=program		\N	4.9.1	\N	\N	9392011581
1	Jacob	db/changelogs/20220421-01-changelog.xml	2022-08-01 22:13:31.950825	25	EXECUTED	8:4e933d0510bbf655e973756e15a559fb	insert tableName=transaction_type; insert tableName=transaction_type		\N	4.9.1	\N	\N	9392011581
1	Jacob	db/changelogs/20220730-01-changelog.xml	2022-08-01 22:13:31.955757	26	EXECUTED	8:683eb7a32261a01e47d1b1400dba0229	modifyDataType columnName=smpl_chain_wallet_address, tableName=member		\N	4.9.1	\N	\N	9392011581
\.


--
-- Data for Name: databasechangeloglock; Type: TABLE DATA; Schema: public; Owner: AmbassadorProgram
--

COPY public.databasechangeloglock (id, locked, lockgranted, lockedby) FROM stdin;
1	f	\N	\N
\.


--
-- Data for Name: member; Type: TABLE DATA; Schema: public; Owner: AmbassadorProgram
--

COPY public.member (id, parent_member_id, smpl_chain_wallet_address, date_created, program_id) FROM stdin;
1	0	smpl1amjrtwxjtngwgsfun6xgmr9ut8v4v9dh6c0nsd	2022-08-01 22:15:48.916797	1
\.


--
-- Data for Name: program; Type: TABLE DATA; Schema: public; Owner: AmbassadorProgram
--

COPY public.program (id, name, vendor_id) FROM stdin;
1	Ambassador Program	1
\.


--
-- Data for Name: program_wallet; Type: TABLE DATA; Schema: public; Owner: AmbassadorProgram
--

COPY public.program_wallet (id, distribution_address, smpl_chain_wallet_address, program_id) FROM stdin;
\.


--
-- Data for Name: transaction; Type: TABLE DATA; Schema: public; Owner: AmbassadorProgram
--

COPY public.transaction (id, smpl_transaction_id, transaction_amount, transaction_date, member_id, purchasing_member_id, transaction_type_id) FROM stdin;
\.


--
-- Data for Name: transaction_type; Type: TABLE DATA; Schema: public; Owner: AmbassadorProgram
--

COPY public.transaction_type (id, name) FROM stdin;
1	Blockchain
2	Reward
\.


--
-- Data for Name: vendor; Type: TABLE DATA; Schema: public; Owner: AmbassadorProgram
--

COPY public.vendor (id, name) FROM stdin;
1	Smpl Foundation
\.


--
-- Name: ambassador_details_id_seq; Type: SEQUENCE SET; Schema: public; Owner: AmbassadorProgram
--

SELECT pg_catalog.setval('public.ambassador_details_id_seq', 1, true);


--
-- Name: member_id_seq; Type: SEQUENCE SET; Schema: public; Owner: AmbassadorProgram
--

SELECT pg_catalog.setval('public.member_id_seq', 1, true);


--
-- Name: program_id_seq; Type: SEQUENCE SET; Schema: public; Owner: AmbassadorProgram
--

SELECT pg_catalog.setval('public.program_id_seq', 1, false);


--
-- Name: program_wallet_id_seq; Type: SEQUENCE SET; Schema: public; Owner: AmbassadorProgram
--

SELECT pg_catalog.setval('public.program_wallet_id_seq', 1, false);


--
-- Name: transaction_id_seq; Type: SEQUENCE SET; Schema: public; Owner: AmbassadorProgram
--

SELECT pg_catalog.setval('public.transaction_id_seq', 1, false);


--
-- Name: transaction_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: AmbassadorProgram
--

SELECT pg_catalog.setval('public.transaction_type_id_seq', 1, false);


--
-- Name: vendor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: AmbassadorProgram
--

SELECT pg_catalog.setval('public.vendor_id_seq', 1, false);


--
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: public; Owner: AmbassadorProgram
--

ALTER TABLE ONLY public.databasechangeloglock
    ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);


--
-- Name: ambassador_details pk_ambassador_details; Type: CONSTRAINT; Schema: public; Owner: AmbassadorProgram
--

ALTER TABLE ONLY public.ambassador_details
    ADD CONSTRAINT pk_ambassador_details PRIMARY KEY (id);


--
-- Name: member pk_member; Type: CONSTRAINT; Schema: public; Owner: AmbassadorProgram
--

ALTER TABLE ONLY public.member
    ADD CONSTRAINT pk_member PRIMARY KEY (id);


--
-- Name: program pk_program; Type: CONSTRAINT; Schema: public; Owner: AmbassadorProgram
--

ALTER TABLE ONLY public.program
    ADD CONSTRAINT pk_program PRIMARY KEY (id);


--
-- Name: program_wallet pk_program_wallet; Type: CONSTRAINT; Schema: public; Owner: AmbassadorProgram
--

ALTER TABLE ONLY public.program_wallet
    ADD CONSTRAINT pk_program_wallet PRIMARY KEY (id);


--
-- Name: transaction pk_transaction; Type: CONSTRAINT; Schema: public; Owner: AmbassadorProgram
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT pk_transaction PRIMARY KEY (id);


--
-- Name: transaction_type pk_transaction_type; Type: CONSTRAINT; Schema: public; Owner: AmbassadorProgram
--

ALTER TABLE ONLY public.transaction_type
    ADD CONSTRAINT pk_transaction_type PRIMARY KEY (id);


--
-- Name: vendor pk_vendor; Type: CONSTRAINT; Schema: public; Owner: AmbassadorProgram
--

ALTER TABLE ONLY public.vendor
    ADD CONSTRAINT pk_vendor PRIMARY KEY (id);


--
-- Name: transaction_type uc_776f680af5de038e995b11711; Type: CONSTRAINT; Schema: public; Owner: AmbassadorProgram
--

ALTER TABLE ONLY public.transaction_type
    ADD CONSTRAINT uc_776f680af5de038e995b11711 UNIQUE (name);


--
-- Name: program_wallet uc_77f53c26c241950bb29b13015; Type: CONSTRAINT; Schema: public; Owner: AmbassadorProgram
--

ALTER TABLE ONLY public.program_wallet
    ADD CONSTRAINT uc_77f53c26c241950bb29b13015 UNIQUE (smpl_chain_wallet_address);


--
-- Name: vendor uc_8b620b42a99ff4cda0a6b8cc0; Type: CONSTRAINT; Schema: public; Owner: AmbassadorProgram
--

ALTER TABLE ONLY public.vendor
    ADD CONSTRAINT uc_8b620b42a99ff4cda0a6b8cc0 UNIQUE (name);


--
-- Name: program uc_9a45533329d6651ba500ac344; Type: CONSTRAINT; Schema: public; Owner: AmbassadorProgram
--

ALTER TABLE ONLY public.program
    ADD CONSTRAINT uc_9a45533329d6651ba500ac344 UNIQUE (vendor_id, name);


--
-- Name: ambassador_details uc_ambassador_details_referral_code; Type: CONSTRAINT; Schema: public; Owner: AmbassadorProgram
--

ALTER TABLE ONLY public.ambassador_details
    ADD CONSTRAINT uc_ambassador_details_referral_code UNIQUE (referral_code);


--
-- Name: member uc_fa4cd0b19f045539972f86cd9; Type: CONSTRAINT; Schema: public; Owner: AmbassadorProgram
--

ALTER TABLE ONLY public.member
    ADD CONSTRAINT uc_fa4cd0b19f045539972f86cd9 UNIQUE (smpl_chain_wallet_address);


--
-- Name: idx_0743ddfef21ec86529da92baa; Type: INDEX; Schema: public; Owner: AmbassadorProgram
--

CREATE UNIQUE INDEX idx_0743ddfef21ec86529da92baa ON public.ambassador_details USING btree (referral_code);


--
-- Name: idx_94cc9117908d8719763c23bff; Type: INDEX; Schema: public; Owner: AmbassadorProgram
--

CREATE INDEX idx_94cc9117908d8719763c23bff ON public.transaction USING btree (member_id, transaction_date);


--
-- Name: idx_f578c838501976455ff38cabb; Type: INDEX; Schema: public; Owner: AmbassadorProgram
--

CREATE INDEX idx_f578c838501976455ff38cabb ON public.member USING btree (parent_member_id);


--
-- Name: ambassador_details fk_ambassador_details_on_member; Type: FK CONSTRAINT; Schema: public; Owner: AmbassadorProgram
--

ALTER TABLE ONLY public.ambassador_details
    ADD CONSTRAINT fk_ambassador_details_on_member FOREIGN KEY (member_id) REFERENCES public.member(id);


--
-- Name: member fk_member_on_program; Type: FK CONSTRAINT; Schema: public; Owner: AmbassadorProgram
--

ALTER TABLE ONLY public.member
    ADD CONSTRAINT fk_member_on_program FOREIGN KEY (program_id) REFERENCES public.program(id);


--
-- Name: program fk_program_on_vendor; Type: FK CONSTRAINT; Schema: public; Owner: AmbassadorProgram
--

ALTER TABLE ONLY public.program
    ADD CONSTRAINT fk_program_on_vendor FOREIGN KEY (vendor_id) REFERENCES public.vendor(id);


--
-- Name: program_wallet fk_program_wallet_on_program; Type: FK CONSTRAINT; Schema: public; Owner: AmbassadorProgram
--

ALTER TABLE ONLY public.program_wallet
    ADD CONSTRAINT fk_program_wallet_on_program FOREIGN KEY (program_id) REFERENCES public.program(id);


--
-- Name: transaction fk_transaction_on_member; Type: FK CONSTRAINT; Schema: public; Owner: AmbassadorProgram
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT fk_transaction_on_member FOREIGN KEY (member_id) REFERENCES public.member(id);


--
-- Name: transaction fk_transaction_on_transaction_type; Type: FK CONSTRAINT; Schema: public; Owner: AmbassadorProgram
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT fk_transaction_on_transaction_type FOREIGN KEY (transaction_type_id) REFERENCES public.transaction_type(id);


--
-- Name: transaction purchasingmemberkey; Type: FK CONSTRAINT; Schema: public; Owner: AmbassadorProgram
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT purchasingmemberkey FOREIGN KEY (purchasing_member_id) REFERENCES public.member(id);


--
-- PostgreSQL database dump complete
--

